### ISSUE TITLE
The code hangs on during  multi GPU training

### ISSUE THREAD

**Issue by RhythmOfTheRain-Byte** [CVMI-Lab/ST3D#79]
Excuse me. I'm getting code hangs during multi GPU training. Is anyone else having this problem?
The command line is as fellows:
bash toos/scrits/dist train sh 4 ..fo fie homeestar/proiects/ST3/to0s/Cfas/da-nuscenes-kitti models/secondiou/secondiou old anchor.yaml
Thank you!

**Comment by Dysinia** [comment]
You can try the train.py instead of dist_train until train.py outputs a ckpt. I met the same problem and find that it was caused by data architecture.

**Comment by RhythmOfTheRain-Byte** [comment]
OK thank you，I will try it！

**Comment by fdy61** [comment]
@RhythmOfTheRain-Byte Hello, have you solved it? I have met the same problem as yours. The picture is below:
![image](https://github.com/CVMI-Lab/ST3D/assets/134828384/e4daf7fb-8a89-4ea6-9b87-e86b94785f45)

**Comment by ZSA010807** [comment]
> @RhythmOfTheRain-Byte Hello, have you solved it? I have met the same problem as yours. The picture is below: ![image](https://private-user-images.githubusercontent.com/134828384/341938686-e4daf7fb-8a89-4ea6-9b87-e86b94785f45.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNDY3NjUsIm5iZiI6MTcyMTA0NjQ2NSwicGF0aCI6Ii8xMzQ4MjgzODQvMzQxOTM4Njg2LWU0ZGFmN2ZiLThhODktNGVhNi05Yjg3LWU4NmI5NDc4NWY0NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxNVQxMjI3NDVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZDQ2OTFiOTczODE4Nzg2MGYzOTdhYTNhZjc3YmQ1Zjg1YWU1MzJmNTM5YjI2ZGEwNjhlNGJiZmRjYzM3NTIzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CHGF19gqfYP1oOEsyHPPQMd6eWN9Af8oSIGILmWeyKI)

Hello，I also have met this problem，do you know the solution now?

**Comment by fdy61** [comment]
@ZSA010807  I run it with just a single GPU and it won't get stuck.

**Comment by ZSA010807** [comment]
> @ZSA010807 I run it with just a single GPU and it won't get stuck.

Thank you for your reply，I have tried with a single GPU and it works successfully. But due to the limited GPU memory, I have to use multiple GPUs.

**Comment by fdy61** [comment]
@ZSA010807 Make the batch size smaller will solve this problem.

**Comment by ZSA010807** [comment]
> @ZSA010807 Make the batch size smaller will solve this problem.

OK,I will try it
